<?php

return [
    "top_h1" => "Eine Reise tief in das armenische Land – Berge, fruchtbare Täler, Klöster, uralte Zivilisation, einmaliges Alphabet … - Armenien, das Land, aus dem ich komme, die Perle des Kaukasus voll von Schätzen. Seine freundlichen Menschen freuen sich, Sie in meiner Agentur begrüssen zu dürfen. Warten Sie nicht mehr, um eine Wahl zwischen unseren Touren zu treffen!" ,
    "popup_h1" => "Über Armenien" ,
    "popup_p" => "Land der Kultur, Geschichte und Legenden, die von Generation zu Generation weitergegeben wurden - das bin ich Hajastan, Land von Hajk, dem Urvater und Gründer der armenischen Nation. Ich befinde mich im Kleinkaukasus zwischen Europa und Asien, aber meine Grösse ist nur ein Zehntel meines Herkunftsgebiets. Haben Sie schon einmal über Armenien gehört? Wenn ich Ihnen über Charles Aznavour erzähle, dann ja. Wenn ich Ihnen über Garni, Sewan, Etschmiadsin, Gjumri erzähle? Ist es kein guter Grund, dorthin zu fahren und diese Orte zu entdecken? <br><br>
Armenien ist die Wiege einer der ältesten Zivilisationen der Welt und das erste christliche Land (301). Seine abwechslungsreichen Landschaften und seine Geschichte machen es zu einem idealen Ziel für diejenigen, die kulturelle Entdeckungen und das Erbe mit Wandern und Reiten kombinieren möchten. <br><br>
Atmen Sie die Luft der Hochebenen, bewundern Sie den Berg Ararat, das Nationalsymbol Armeniens und besuchen Sie die Klöster, die mit Chatschkars (Kreuzsteine) geschmückt sind: ein einzigartiges armenisches Kulturerbe. Entdecken Sie die wichtigsten kulturellen Erscheinungen dieser Gegend! Vielleicht haben Sie schon die lokale armenische Küche, die Ihnen Aromen voller Sonne und frischer Luft bietet, gekostet. <br><br>
Armenien hat noch andere Überraschungen für Sie: Jerewan und seine zahlreichen Museen, darunter Matenadaran, welches eine der grössten Sammlungen alter Handschriften der Welt enthält, Sewansee, einer der grössten Süsswasser-Hochgebirgseen in Eurasien und zu guter Letzt lokale traditionelle christliche Feiertage wie Ostern und Weihnachten, die nach dem Kalender der Apostolischen Kirche gefeiert werden. Tanzen Sie zum Rhythmus des typisch armenischen Instrumentes „Duduk“ oder besuchen Sie Konzerte, um den orientalischen und bezaubernden Klang zu geniessen! Lernen Sie Armenisch kennen - eine einzigartige Sprache und eine Schrift, auf die Armenier stolz sind. Armenien hat noch viel mehr zu bieten! <br><br>
Armenien ist auch für seine Grenze an Georgien und Iran interessant. Es ist durchaus möglich, die Reise nach Armenien mit einem dieser Länder zu kombinieren. Sie werden die Ähnlichkeiten und Unterschiede bemerken, die Ihnen mehr über die tausendjährige Geschichte des alten Königreichs von Armenien oder Grossarmenien erzählen werden, das seinen Höhepunkt unter Tigran dem Grossen (95-55 v. Chr.) erreichte. <br><br>
Nach langen Invasionen von Römern, Sassaniden, Byzantinern, Osmanen, Persen und Russen hat Armenien 1991, nach dem Zusammenbruch der UdSSR, seine endgültige Unabhängigkeit erreicht. Am 8. Mai 2018 wurde der Oppositionsführer Nikol Paschinjan vom armenischen Parlament zum Premierminister ausgewählt. Es läutete eine neue politische und demokratische Ära ein, ein Ausbruch der Hoffnung für das armenische Volk und die Welt. <br><br>
Für Ihre luxuriöse Individualreise bieten wir Luxusreisen in Begleitung von VIP-Reiseführern an.  
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Armenien, hochwertige Dienstleistungen in Armenien, luxuriöse Tours in Armenien, luxuriöse Hotels in Armenien, luxuriöse Reise nach Armenien, Reisespezialist für  Armenien, VIP Reiseführer in Armenien, VIP Reisebegleitung in Armenien , erstklassige Reiseberatung für Armenien, Tour Spezialist für Armenien, live Resieführer in Armenien",
    "title" => "Tours in Armenien: massgeschneidert und gut organisiert| Orient Travel" ,
    "meta_description" => "Thematische Reisen in Armenien: Entdeckung des historischen und kulturellen Erbes, Wandern, Reiten, Kontakte und Austausch mit der Bevölkerung und Eintauchen in ihr tägliches Leben und lokale Traditionen." ,
];

 
