<?php

return [
    "top_h1" => "Georgien – dieses an der Grenze des Grossen Kaukasus gelegene Land bietet erstaunliche und faszinierende Überraschungen. Landschaften mit einmaligen Farben, schneebedeckte Bergspitzen, Alpenseen, Weinberge, Klöster, antike Stätten und Höhlenbewohner. Individuelle Reisen 100% zuverlässig und garantiert." ,
    "popup_h1" => "Über Georgien" ,
    "popup_p" => "Zögern Sie, nach Europa oder Asien zu fahren? Dann wählen Sie Georgien!  <br><br>
Als Kreuzungspunkt auf der Seidenstrasse ist Georgien ein Knotenpunkt von Zivilisationen und Kulturen, die einander gefolgt und die heutigen gemischten Traditionen gebildet haben, die sich im Erbe des Landes widerspiegeln. Georgien ist mysteriös, weil es nicht sehr touristisch ist. Es überrascht aber durch seine Berglandschaften, Kirchen, Klöster und seine tausendjährige Geschichte, einzigartige Schrift und Sprache, gastfreundlichen Menschen. Wenn Sie sich für Natur oder Kultur interessieren, bietet das Land mehr als Sie erwarten. <br><br>
Moderne und Tradition kommen zusammen und hinterlassen bei den Besuchern einen erstaunlichen Eindruck. Sie können in die Berge, Wälder, Steppen fliehen, an den Seen oder in Weinbaugebieten spazieren. Georgien ist berühmt für seinen Wein und seine Gastronomie: Chinkali, Tschakapuli, Saziwi, Lobiani, Kubdari, Chatschapuri - so viele Gerichte, die mit Fleisch, Gemüse, Gewürzen, Käse zubereitet werden ... Geniessen Sie außergewöhnliche Aromen, Mischungen aus kaukasischen, europäischen, orientalischen und sowjetischen Küchen! Sie werden es lieben! <br><br>
Beeilen Sie sich und entdecken Sie die Höhlen von Uplisziche und Wardsia, den Klosterkomplex von Dawit Garedscha, zahlreiche Festungen, die Städte Gori, Mzcheta (die alte Hauptstadt), Borjomi, berühmt für seine Heilbäder, Kutaissi und seinen Markt, Stepanzminda und viele andere interessante Orte. Sie würden gerne ein paar Nächte in Tiflis, in der derzeitigen Hauptstadt des Landes verbringen indem Sie durch die alten Strassen von Tiflis bummeln, einen Blick auf die Friedensbrücke mit moderner Architektur werfen und die in der ganzen Stadt verstreuten Kirchen besuchen, auf die sich eine fantastische Aussicht von der Festung Nariqala öffnet! Entdecken Sie auch die Schwefelbäder, die für ihr Thermalwasser bekannt sind! Erfahren Sie mehr über den Mythos vom „Goldenen Vlies“ und besuchen Sie die Schätze von Altgeorgien im Nationalmuseum. <br><br>
Georgien ist sicher einem Besuch wert! Zögern Sie also nicht, sich für eine erstklassige massgeschneiderte Reise mit einem professionellen Reiseführer nach Georgien zu entscheiden. Wir bieten Ihnen hochwertige Dienstleistungen. 
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Georgien, hochwertige Dienstleistungen in Georgien, luxuriöse Tours in Georgien, luxuriöse Hotels in Georgien, luxuriöse Reise nach Georgien, Reisespezialist für  Georgien, VIP Reiseführer in Georgien, VIP Reisebegleitung in Georgien , erstklassige Reiseberatung für Georgien, Tour Spezialist für Georgien, live Resieführer in Georgien",
    "title" => "Reisen nach Georgien: in einer Gruppe oder individuell | Orient Travel" ,
    "meta_description" => "Entdecken Sie Georgien durch thematische Touren, die Ihnen die besten und schönsten Ecken dieses fabelhaften Landes zeigen! Luxuriöse Touren abseits der ausgetretenen Pfade dank kompetenter und freundlicher lokaler Guides. Begleitung nach Mass garantiert!" ,
];
 
