<?php

return [
    "top_h1" => "Iran gestern und heute – Wagen Sie es, dieses legendäre Land in Begleitung eines Experten zu entdecken. Lassen Sie sich durch den Faden der Geschichte führen und wir werden aus diesem Faden alles weben, was Sie möchten. Kulturelle Besuche, einzigartige Wanderungen sind ein Teil des Programms, das ich für Sie erstellen werde." ,
    "popup_h1" => "Über Iran" ,
    "popup_p" => "Als Touristenziel ist Iran zwar weniger populär als seine kaukasischen Nachbarn, aber es ist eines der Länder, das über große architektonische und landschaftliche Schätze besitz, die seine tausendjährige und multikulturelle Vergangenheit widerspiegeln. Iran - Land der Imperien, die sich im Laufe der Zeit gefolgt haben. Heute ist es ein Entwicklungsland mit 80 Millionen Einwohnern, das man besuchen „muss“. Um  das alte Persien zu entdecken, blättern Sie die Seiten von „Tausend und eine Nacht“ durch und erkunden Sie die Kronjuwelen, Moscheen, Paläste, Gärten, Parks, Zitadellen, Basare, Städte und Dörfer, die einfach magisch wirken.  <br><br>
Eine Luxusreise im Iran begleitet von einem professionellen Reiseführer garantiert Ihnen den besten Aufenthalt! Wir bieten massgeschneiderte Touren abseits der ausgetretenen Pfade. <br><br>
Kaschan, eine schöne Oasenstadt, die man nicht verpassen soll, ist das Vorwort unserer Reise durch die iranischen Wüsten. In einem Land, wo das Wasser knapp ist, haben die Iraner mehr als 33.000 Qānats (unterirdische Kanäle für den Zugang zum Grundwasser) gebaut, elf von denen dank ihrer Einzigartigkeit auf der UNESCO-Liste des Weltkulturerbes stehen. Die ältesten unterirdischen Tunnels sind mehr als 2500 Jahre alt und mehrere Kilometer lang. Sie sind vorgesehen, um das Grundwasser zu erreichen und es auf das Land zu verteilen.   <br><br>
Zu den anderen faszinierenden Eigenschaften dieses trockenen Landes gehören die Gletscher, die man auf dem Weg durch das Zāgros-Gebirge, Elburs, den höchsten Gipfel im Iran und Damawand trifft. Ein anderes Reiseziel ist die mehr als 2000 Jahre alte Stadt Yazd, wo die Karawanen entlang der berühmten Seidenstrasse gingen und Iran mit China verbanden. <br><br>
Hier, in der Stadt Yazd, können Sie die Bâdgirs oder ''Windtürme'' sehen, ein architektonisches Element an der Spitze der Wohnungen, das vor mehreren Jahrhunderten geschaffen wurde und für die Regulation der Innentemperatur durch ein ausgeklügeltes Lüftungskühlsystem vorgesehen war. <br><br>
Erfahren Sie mehr über den Zoroastrismus, eine vorislamische Religion, die immer noch von fast 30.000 Iranern praktiziert wird. Geniessen Sie die würzigen und warmen Gerüche der Sommernächte. Verkosten Sie die farbenfrohen kulinarischen Köstlichkeiten der lokalen Küche. Erkunden Sie die Städte der Legenden wie Isfahan, die romantische Schiras, die archäologischen Stätten von Persepolis, nicht zu vergessen Teheran - die moderne Hauptstadt des Landes - wo Sie die Museen besuchen können, wie das Teppichmuseum, das für seine Sammlung von fast 7000 persischen Teppichen aus dem 18. Jahrhundert bis zu unseren Zeiten bekannt ist. <br><br>
Buchen Sie Ihren Flug zu diesem erstaunlichen Land und kehren Sie mit hellem Geist zurück!
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Iran, hochwertige Dienstleistungen in Iran, luxuriöse Tours in Iran, luxuriöse Hotels in Iran, luxuriöse Reise nach Iran, Reisespezialist für  Iran, VIP Reiseführer in Iran, VIP Reisebegleitung in Iran , erstklassige Reiseberatung für Iran, Tour Spezialist für Iran, live Resieführer in Iran",
    "title" => "Reisen in den Iran mit spezialisierten Guides | Orient Travel" ,
    "meta_description" => "Es lohnt sich das Land von tausend Schätzen und ein Volk zu treffen, das über jahrtausende Traditionen verfügt. Reisen Sie durch die Vergangenheit und Gegenwart in den Städten Isfahan, Shiras, Persepolis und Teheran, durch majestätische Wüstenlandschaften und ungeahnte Oasen." ,
];