<?php

return [
    "top_h1" => "Kasachstan – Tradition und Moderne treffen sich im Land der Seen, Berge und Steppen. Ganz zu schweigen von Astana, der Hauptstadt mit modernem Ambiente, die Sie noch nie gesehen haben! Tapetenwechsel ist garantiert!" ,
    "popup_h1" => "Über Kasachstan" ,
    "popup_p" => "Entscheiden Sie sich für eine erstklassige Individual- oder Gruppenreise, dann verspricht Ihnen Kasachstan eines der originellsten und unvergesslichsten Erlebnisse in Ihrem Leben. Fünfmal größer als Frankreich, aber viermal weniger bevölkert zieht dieses Gebiet mehr und mehr Reisende an! Das alte Land der Nomaden wurde seit dem 13. Jahrhundert von Mongolen bewohnt. Dieses historische Land ist mit ausgedehnten sandigen, bergigen und grünen Landschaften ausgestattet. Entdecken Sie Kasachstan aus einer anderen Perspektive: von riesigen Steppen bis zu großen Seen!<br><br>
Die Städte Almaty und Turkestan geben Ihnen die Möglichkeit, die glorreiche Vergangenheit der Kameltreiber entlang der Seidenstraße zu erleben. Almaty - ehemalige politische Hauptstadt und derzeit kulturelles Zentrum des Landes - ist sehenswert. Besuchen Sie den Panfilow Park aus dem 19. Jahrhundert, die orthodoxe Zenkow-Kathedrale aus dem frühen 20. Jahrhundert. Der große Almaty-See, die berühmte Eisbahn Medeu und das Skigebiet Chimbulak werden Sie sicher begeistern. Turkestan ist die älteste Stadt des Landes (4.-6. Jh. v. Chr.): Es ist eine Wüstenstadt an der Kreuzung der Perser- und Stammeskulturen. Diese Festungsstadt wurde zum wichtigsten administrativen, kommerziellen und religiösen Zentrum im Mittelalter. Es gilt als das zweite Mekka und beherbergt das Mausoleum des Sufi Ahmed Yesevi (12. Jh.) - ein UNESCO Weltkulturerbe.<br><br>
Astana - die Hauptstadt von Kasachstan seit 1997 - ist ein Beweis für die wirtschaftliche Modernität, die sich im Laufe der Jahre entwickelt hat. Dank ihrer Dynamik in Bezug auf Innovationen in der Architektur hat sich die Stadt zu einem beliebten Reiseziel entwickelt. Machen Sie eine atemberaubende Reise vom Friedens- und Versöhnungspalast zum „Atameken“ Ethnografischen Komplex und dem Bajterek-Turm der Präsidentensiedlung Ark-Oda, um es mit dem Nur Alem Ausstellungskomplex zu beenden - dem größten kugelförmigen Gebäude der Welt!<br><br>
Kasachstan ist perfekt für Naturliebhaber! Die Kolsai-Seen - ''Perlen vom nördlichen Tienschan'' - der größte von ihnen hat eine erstaunliche blaue Farbe und befindet sich auf 2.552 Metern über dem Meeresspiegel. Dieser See verbindet sich mit dem Wasserfall, der ein herrliches Panorama erzeugt. Der Tannenwald und die Almwiesen machen die Luft unvergleichlich frisch. Der 1996 erbaute Nationalpark Altyn-Emel erstreckt sich über 30 km: Seine ''singenden Dünen'', Berge und fein geschnitzte Erosionsfelsen in verschiedenen Farben lagen einst unter dem Meer. Was für eine herrliche Landschaft!<br><br>
Dieses Reiseziel erfüllt die Erwartungen von Geschichtsliebhabern und bietet Ihnen an, die Petroglyphen der Tamgali-Schlucht im Südosten Kasachstans zu entdecken. Eine Sammlung von 5000 Petroglyphen, die älteste geht auf die zweite Hälfte des 2000 v. Chr. zurück, wartet auf Sie.<br><br>
Rufen Sie unser Reisebüro an, um eine erstklassige Reiseberatung zu erhalten und unter allen Umständen die VIP-Reisebegleitung zu nutzen. Sie haben es verdient!" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Kazachstan, hochwertige Dienstleistungen in Kazachstan, luxuriöse Tours in Kazachstan, luxuriöse Hotels in Kazachstan, luxuriöse Reise nach Kazachstan, Reisespezialist für  Kazachstan, VIP Reiseführer in Kazachstan, VIP Reisebegleitung in Kazachstan , erstklassige Reiseberatung für Kazachstan, Tour Spezialist für Kazachstan, live Resieführer in Kazachstan",
    "title" => "Individuelle oder Gruppeneisen in Kasachstan | Orient Travel" ,
    "meta_description" => "Ausflüge, thematische Touren, Wanderungen, kulturelle und historische Entdeckungen in Kasachstan, nomadisches Land mit der glorreichen Vergangenheit, mit der Karawane entlang der Seidenstraße. Besuchen Sie Amalty, Turkestan, Astana, die schönen Kolsay Seen und den Altyn-Emel-Nationalpark!" ,
];


