<?php

return [
    "top_h1" => "Kirgisistan – Grüne und grenzenlose Landschaften, Übernachtungen in Jurten, die Entspannung ist garantiert. Land der Geschichte, folgen Sie den Spuren von Dschinghis Khan und Marco Polo. Sagen Sie nichts mehr, kommen Sie einfach dorthin! Ich kümmere mich um alles!",
    "popup_h1" => "Über Kirgisistan" ,
    "popup_p" => "Haben Sie Lust in die Natur einzutauchen? Dann fliegen Sie in das Land der Nomaden – Kirgisistan. <br><br>
Neben seinem Namen, der an die majestätische UdSSR erinnert, verdient dieses Land natürlich grosse Aufmerksamkeit. Kirgisistan ist ein wertvolles Schatz, denn drei Viertel der Landesfläche bilden die Berglandschaften. Entspannen Sie sich und treffen Sie sich mit Halbnomaden, Hirten und Pferden, die wichtige Symbole des Landes sind. Die russischen, chinesischen und muslimischen Einflüsse haben dem Land unglaubliche architektonische Wunder geschenkt. <br><br>
Beginnen Sie Ihre erstklassige Reise von Bischkek - der kirgisischen Hauptstadt. Gönnen Sie sich Momente der Ruhe und Entdeckung in seinen zahlreichen Museen und Theatern sowie geniessen Sie die orientalischen Basare. Setzen Sie sich auf den Weg in die Bergregionen des Landes: Schluchten, Seen, Weiden, Bergkämme und archäologische Stätten, die auf Sie warten! Möchten Sie in der Natur schlafen? Unterkunft und Übernachtung in einer Jurte gehören zum Programm und versetzen Sie in das Paradies! Wir bieten hochwertige Dienstleistungen, um all Ihre Träume zu erfüllen! <br><br>
Erwachen Sie in der Umarmung der majestätischen Berge von Pamir und Tian Shan („Himmlische Berge“), deren Gipfel über 7.000 Metern in den Himmel ragen. Im Herzen der Berge beherbergt die Stadt Karakol eine Moschee aus den Jahren 1907-1910, die vom chinesischen Architekten Ejoi Si mit einem einzigen Nagel aus Holz gebaut wurde. In der Region befindet sich auch Tscholponata - der grösste Badeort in Zentralasien: Legen Sie sich an die weissen Sandstrände hin und erkunden Sie das 42 Hektar grosse Freilichtmuseum oder „Steingarten“ mit Petroglyphen aus 2000 Jahren v. Chr. und Grabstätten. Die Perle Kirgisistans heisst Yssykköl („warmer See“ auf Kirgisisch) und hat türkisblaues heilendes Salzwasser (1600 m ü. M.). Einzigartig auf der Welt ist es einer der vielen Seen des Landes wie Alaköl und Songköl, der zweitgrösste See (3013 m ü. M.). <br><br>
Kirgisistan, Land der Legenden und Geschichte, hat die Fußstapfen von Dschinghis Khan und Marco Polo auf eigenen Wegen gespürt. Als einst ein wichtiger Teil der Seidenstrasse hatte das Land einige Karawansereien wie Tasch Rabat in 3200 Metern Höhe errichtet. In Osch, der zweitgrössten Stadt des Landes, können Sie den Osch-Basar besuchen, der ein guter Hinweis auf die Vergangenheit des Landes ist. Es ist einer der grössten Märkte in Zentralasien, in einer Stadt, die nach der Legende vom König Solomon vor 3000 Jahren gegründet wurde. Ausserdem wurde sein Thron Suleiman-Too Berg auf der UNESCO-Welterbeliste eingetragen. <br><br>
Haben Sie sich schon entschieden? 
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Kirgisistan, hochwertige Dienstleistungen in Kirgisistan, luxuriöse Tours in Kirgisistan, luxuriöse Hotels in Kirgisistan, luxuriöse Reise nach Kirgisistan, Reisespezialist für  Kirgisistan, VIP Reiseführer in Kirgisistan, VIP Reisebegleitung in Kirgisistan , erstklassige Reiseberatung für Kirgisistan, Tour Spezialist für Kirgisistan, live Resieführer in Kirgisistan",
    "title" => "Individuelle und Gruppenreisen in Kirgisistan | Orient Travel" ,
    "meta_description" => "Ein bergiges Land, Erbe des Nomadentums, zwischen Bischkek, dem Pamir, Tscholponata, dem türkisfarbenen See von Yssykköl, Basar von Osch. Wir organisieren Ausflüge in kleinen Gruppen oder individuell durch die Hauptpunkte des Landes. Unterkunft unter Jurte und unbeschreibliche Wanderungen." ,
];


