<?php

return [
    "top_h1" => "Mongolei – Charme und Majestät sind zwei Wörter, die ausreichend sind, um dieses durch unendliche Steppen bedeckte Land zu beschreiben. Die Besonderheit Ihres Aufenthalts ist Ihr Wunsch, die charakteristischen Merkmale des Landes möglichst einfach und authentisch zu verbringen. Treffen Sie die Einheimischen und geniessen Sie die Gerüche, die der Wind bei jedem Schritt mit sich bringt … Fühlen Sie die Luft ..." ,
    "popup_h1" => "Über die Mongolei" ,
    "popup_p" => "Die Steppen dieses riesigen Landes sind von Bergen umgeben, die seine Nomaden so weit sehen, wie das Auge reicht. Sie können hier und da Jurten oder auf dem Rasen grasende Pferde sehen, was eine seltene Szene ist. Eine Reise in die Mongolei beruhigt den Geist, denn dort erzählt die Stille der Natur vom Rhythmus des einheimischen Alltagslebens. Stellen Sie sich mal vor, mit der Natur und dem Universum in Verbindung zu treten, Sie werden nicht enttäuscht sein. Ausser der Übernachtung in einer Jurte können Sie auch einen Pferd oder ein Kamel reiten oder zu Fuß die Ebenen, Berge, Wälder und Wüsten durchqueren, die das mongolische Territorium ausmachen.<br><br>
Die Mongolei, das ehemalige Zentrum des mongolischen Reiches im 13. Jahrhundert, erlangte ihre Unabhängigkeit erst 1911 nach der jahrhundertelangen chinesischen Herrschaft. Seine Geschichte hat Spuren auf der Architektur und Kultur des Landes insbesondere durch buddhistische Klöster hinterlassen. Besuchen Sie das buddhistische Kloster Gandan in Ulaanbaatar, der Hauptstadt des Landes, oder entdecken Sie die ältesten - Erdene Dsuu in Karakorum und auch Amarbajasgalant gegründet im Jahr 1736. <br><br>
Ob Sie eine individuelle, Gruppen-, organisierte oder personalisierte Reise wählen, wir bringen Sie zu den schönsten Orten des Landes. Die Berge sind ein Muss für ihre Wildnis. Die Bergkette des Altai ist mit seinen 4000 m Gipfeln der Ort, wo das einzige muslimische Volk der Mongolei – Kasachen leben. Zorgol Chairchan, der heilige Berg der Mongolen, ist reich an Höhlen und Wasserquellen. Erkunden Sie die Berge von Baga Gazriin Chuluu, eine Granitfelsenformation mit historischen Höhlen. Wenn Sie mehr über die Geschichte des Landes erfahren möchten, laden wir Sie ein, den Nationalpark Tavan Bogd mit seinen Lärchenwäldern, kleinen Seen und Petroglyphen zu besuchen, die zum Weltkulturerbe der UNESCO gehören. <br><br>
Entdecken Sie die vielen blauen Seen des Landes wie Uwsgul, Tsagaan Nuur und Chöwsgöl, im Gegensatz zu der riesigen Wüste Gobi, die ein Drittel der gesamten Fläche der Mongolei bedeckt! Sie werden beeindruckt sein von den singenden Dünen von Chongor, die von einer kleinen Oase gesäumt sind. Mit welchem Ort würden Sie anfangen, wenn Sie eine Chance hätten? Würden Sie mit einem Kamelritt beginnen, um die Nomaden zu entdecken, oder vielleicht mit einem Besuch im Gobi Gurwan Saichan Nationalpark? Würde Sie die Teilnahme an den traditionellen Festen reizen, wie das Adlerfest in der Provinz Bajan-Ölgii, das jedes Jahr am ersten Oktoberwochenende gefeiert wird? <br><br>
Treffen Sie Ihre Wahl, gehen Sie in die Mongolei! Wir freuen uns, Ihnen erstklassige Reiseberatung und hochwertige Dienstleistungen zu bieten." ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Mongolei, hochwertige Dienstleistungen in Mongolei, luxuriöse Tours in Mongolei, luxuriöse Hotels in Mongolei, luxuriöse Reise nach Mongolei, Reisespezialist für  Mongolei, VIP Reiseführer in Mongolei, VIP Reisebegleitung in Mongolei , erstklassige Reiseberatung für Mongolei, Tour Spezialist für Mongolei, live Resieführer in Mongolei",
    "title" => "Individuelle oder Gruppeneisen in Mongolei | Orient Travel" ,
    "meta_description" => "Ausflüge durch ein grosses Land, wo Steppen von Bergen umgeben sind. Erkunden Sie die Natur, schlafen Sie in Jurten, um die Mongolen zu treffen! Lernen Sie die Stille der Wüste Gobi kennen, besuchen Sie Ulaanbaatar, die buddhistischen Tempel und bewundern Sie die vielen Seen wie Khuvsgul!" ,
];

