<?php

return [
    "top_h1" => "Tadschikistan – Machen Sie Ihre Reise im Herzen eines der schönsten Gebirgsländer der Welt zu einer unvergesslichen Erinnerung. Der Pamir – das Dach der Welt, mit türkisfarbenen Seen, heissen Quellen, Moscheen, seinem Nationalpark … Schenken Sie dieser Reise einige Tage, denn es gibt zu viele Landschaften, um während einer Reise entdeckt zu werden. Sie werden nie enttäuscht!",
    "popup_h1" => "Über Tadschikistan" ,
    "popup_p" => "Möchten Sie die Zeit beim Reisen vergessen, die stärksten Schwingungen der Mutter Erde in den Bergen ergreifen, die Grenzenlosigkeit der Natur spüren, wie Sie es noch nie zuvor erlebt haben? Dann müssen Sie mindestens einmal in Ihrem Leben nach Tadschikistan reisen! Ohne Zweifel bleibt das Land einer der unberührtesten Orte. Die Reise nach Tadschikistan ist ein Geschenk für Ihren Körper und Geist. <br><br>
Wandern Sie mit einem Fachführer im Tadschikistan auf dem Pamir-Plateau mit seinen drei über 7000 Meter hohen Gipfeln, unbeschreiblich schönen, türkisfarbenen Seen, Wüsten, fruchtbaren Ebenen und Gletschern. Fast drei Millionen Hektar des Nationalparks, einer der unberührtesten Parks der Welt, gehören zum UNESCO Weltkulturerbe. Verpassen Sie nicht die Seen Bulunkul, Jaschilkul, Karakul, Nurek und ihre Dämme, antike Karawansereien von Nikolajewski und Basch Gumbes. Das Dorf Langar mit seinen 6.000 Petroglyphen in steilen, felsigen Hügeln ist eine Perle am Ende des Wachan-Tals. Die heißen Quellen von Gharm-Chasma, Bibi Fatima und Jelandy lassen Sie unvergessliche Momente erleben. <br><br>
Die Fan-Gebirge im Nordwesten von Duschanbe sind auch ein ideales Ziel für Trekking, wo Sie die sieben Seen von Marguzor sowie Pandschakent, das ''Pompeji Zentralasiens'' - antike Stadt des 5. Jahrhunderts in Sogdien entdecken können. <br><br>
Wenn Sie die Moderne vermissen, verbringen Sie ein paar Tage in Duschanbe - der Hauptstadt des Landes. Besuchen Sie das Denkmal von Ismail Samani - dem Begründer der Samaniden-Dynastie (874-999), die Haji-Yakub-Moschee, den zentralen Pflanzengarten, den Rudaki Nationalpark und das Nationalmuseum für Altertum und Ethnographie.Im Norden von Duschanbe kontrastiert Istarawschan mit der Altstadt - eine der ältesten in Zentralasien und eine der unberührtesten in Tadschikistan. Das Mausoleum von Hazratischach, die blaue Moschee-Medrese von Kok Gumbaz (15. Jahrhundert) sowie die Überreste von Mugh Teppa (2.-7. Jahrhundert) sind auch sehenswert. Auf dem Weg nach Norden hat Chudschand, die zweite Stadt des Landes, die von Alexander dem Großen im 4. Jahrhundert v. Chr. gegründet wurde, seine Zitadelle aus dem 10. Jahrhundert erhalten. Besuchen Sie das Stadtmuseum, den Pandschschanbe-Bazar und den Sheikh Massal ad-Din Komplex.<br><br>
Schließlich versäumen Sie Gissar und seine über 2000 Jahre alte majestätische Festung, die Medrese aus dem 15. Jahrhundert und die alte Karawanserei nicht. <br><br>
Es gibt so viele Orte in Tadschikistan zu sehen, dass Sie sicher zurückkehren werden! Wählen Sie Tadschikistan als Ziel Ihres nächsten Urlaubs! Nutzen Sie unseren erstklassigen Service und die erstklassige Reiseberatung, um eine individuelle Tour durch Tadschikistan zu machen.
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Tadschikistan, hochwertige Dienstleistungen in Tadschikistan, luxuriöse Tours in Tadschikistan, luxuriöse Hotels in Tadschikistan, luxuriöse Reise nach Tadschikistan, Reisespezialist für  Tadschikistan, VIP Reiseführer in Tadschikistan, VIP Reisebegleitung in Tadschikistan , erstklassige Reiseberatung für Tadschikistan, Tour Spezialist für Tadschikistan, live Resieführer in Tadschikistan",
    "title" => "Reisen in Tadschikistan, abseits der ausgetretenen Pfade|Orient Travel" ,
    "meta_description" => "Ungewöhnliche Entdeckungstouren in Tadschikistan, abseits der ausgetretenen Pfade, am Pamir-Gebirge und den Fan Bergen. Wandern Sie, um die türkisfarbenen Seen von Bulunkul, Jaschilkul, Karakul und Marguzor Seen zu entdecken! Besuchen Sie historische Stätten Pendschikent, Gissar!" ,
];

