<?php

return [
    "top_h1" => "Turkmenistan – Ein Land, das für seinen unglaublichen Krater, das Land des Feuers genannt wird, Aschgabat, Oasenstädte aus der Zeit der Seidenstrasse, Turkmenistan hat Vieles zu bieten. Egal, ob Sie alleine oder mit Freunden reisen, lassen Sie die ausgetretenen Pfade, um sich in dieses erstaunliche Land zu begeben.",
    "popup_h1" => "Über Turkmenistan" ,
    "popup_p" => "Die Sonne geht über dem Land auf, dessen jahrhundertealte Geschichte, Nomadenkultur und Wüstenstädte denen seiner Nachbarn in Zentralasien nicht untersteht. Da Turkmenistan nur selten erforscht wird, wirkt es mysteriös und hat viele Überraschungen. Die Oasen, alte und moderne Städte, archäologische Stätten und fabelhafte Landschaften sind sowohl in unseren Individual- als auch in den Gruppen-Luxustouren enthalten. <br><br>
Die Reise von Aschgabat ist ein guter Ausgangspunkt, um das Land kennenzulernen, welches Sie mit seiner Modernität begeistern wird. Die Hauptstadt ist mit weißen Marmorgebäuden, hohen Wohntürmen und ungewöhnlichen Monumenten wie dem Bogen der Neutralität geschmückt. Gehen Sie zum Platz der Unabhängigkeit, um den Präsidentenpalast mit einer goldenen Kuppel zu entdecken. Asadi (oder Ertuğrul Gazi) ist eine von vielen interessanten Moscheen, die sehenswert sind. Sammeln Sie Erinnerungen im berühmten Tolkuschka Basar und in den vielen Museen der Stadt, die reich an Schätzen turkmenischer und sowjetischer Kunst sind. <br><br>
Dann besuchen Sie die alten Städte, die das Land berühmt gemacht haben: Nisa - die ehemalige Hauptstadt des Partherreiches (2. Jahrhundert v. Chr.) und ihre Festung (UNESCO Weltkulturerbe) ruhen sich im prächtigen Juwel der turkmenischen Wüste aus.  Gonur Tepe, die legendäre Hauptstadt von Margusch, ist eine der berühmtesten Stätten der Bronzezeit (2300-1600 v. Chr.). Entdecken Sie die Ruinen der Festungen und Tempel sowie die Nekropole Merw aus dem 3. Jahrhundert v. Chr. (UNESCO-Weltkulturerbe) mit einer Reihe von städtischen Zentren. Die älteste und best erhaltene Stadt von den Oasenstädten entlang der Seidenstraße wird Sie noch mehr beeindrucken. Verpassen Sie nicht das einzigartige Mausoleum von Sultan Sandjar (118-1157), das so einzigartig ist wie die Festung Abdullahan-Kala.  <br><br>
Ein weiteres UNESCO-Weltkulturerbe ist die ehemalige Hauptstadt des Kunja-Urgentsch Reiches von Choresm Shah. Das Mausoleum des Turabeg Chanum aus dem 15. Jahrhundert, das Minarett von Kutlug Timur aus dem 11.-14. Jahrhundert, das zu den höchsten mittelalterlichen Minaretten Zentralasiens zählt (60m) und das Mausoleum von Arslan - dem Gründer des vormongolischen Reiches von Chwaresm.   <br><br>
Verlassen Sie Turkmenistan nicht ohne die Karakum-Wüste und ihren berühmten Krater von Derweze, die ''Tore der Hölle'' zu entdecken. Die Wüste, die mehr als die Hälfte des Landes bildet, streichelt Seen und Quellwasser, Berge, Naturschutzgebiete und Badeorte. Sie werden auch die Möglichkeit haben, sich zu dem Naturklang zu entspannen, während Sie das Achal-Tekkiner-turkmenisches Pferd bewundern, das von dem Teke-Turkmenen Stamm 3000 Jahre in der Wüste von Turkmenistan gezüchtet wurde.    <br><br>
Willkommen in Turkmenistan! Dank unserer erstklassigen Reiseberatung in Turkmenistan und hochwertigen Dienstleistungen garantieren wir Ihnen beispiellose VIP-Begleitung!" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Turkmenistan, hochwertige Dienstleistungen in Turkmenistan, luxuriöse Tours in Turkmenistan, luxuriöse Hotels in Turkmenistan, luxuriöse Reise nach Turkmenistan, Reisespezialist für  Turkmenistan, VIP Reiseführer in Turkmenistan, VIP Reisebegleitung in Turkmenistan , erstklassige Reiseberatung für Turkmenistan, Tour Spezialist für Turkmenistan, live Resieführer in Turkmenistan",
    "title" => "Reisen nach Turkmenistan für Gruppen oder Einzelpersonen|Orient Travel" ,
    "meta_description" => "Kreisläufe in kleinen Gruppen oder massgeschneidert. Lokale Reiseführer begleiten Sie vom Anfang bis zum Ende, um die alten und modernen Städte des Landes zu entdecken - Merw, Nisa, Aschgabat - Oase und Karakum Wüste mit dem Krater von Darvaza." ,
];


