<?php

return [
    "top_h1" => "Usbekistan – Eine einmalige Reise ins Land der tausend Farben und sonnigen Legenden. Wüsten, Moscheen von tausend und einer Nacht, freundliche Einheimischen und vieles mehr erwartet Sie. Sie brauchen nur das Ticket zu buchen. ",
    "popup_h1" => "Über Usbekistan" ,
    "popup_p" => "Was würden Sie über kulturelles Erlebnis, Rückkehr in die Vergangenheit und das Eintauchen in ein fabelhaftes Land sagen? Wie wäre es mit einer Luxusreise nach Usbekistan: 3.000 einzigartige Monumente, eine riesige Wüste aus rotem Sand, die an Naturschutzgebiete von Kiefernwäldern grenzt und Berge, die von Bären, Luchsen und sogar Schneeleoparden bewohnt werden. <br><br>
Ein herrliches Land, reich an Farben, Kultur und Landschaft. Usbekistan bietet den Reisenden den besten Urlaub in Zentralasien. Begleitet von einem professionellen Reiseführer folgen Sie den alten Zivilisationen wie ein Historiker, reisen Sie durch die legendären Städte Samarkand, Buchara, Chiwa, Taschkent (die Hauptstadt von Usbekistan mit zwei Millionen Einwohnern) und alle Ecken, die einst betreten wurden. <br><br>
Mit nur 10 % der Fläche, die derzeit für die Landwirtschaft genutzt wird, ist Usbekistan meist ein Wüstenland. Die beiden Hauptflüsse – Amudarja und Syrdarja – kompensieren den Wassermangel, der durch die Austrocknung des Aralsees, der einst die Entwicklung der Städte und Zivilisationen in Zentralasien, Sogdien, Choresmien und Dawan ermöglichte, verschlimmert wurde. <br><br>
Die Reiserouten der Städte, die Sie besuchen möchten, umfassen Mausoleen, Medressen und Moscheen mit blauen Kuppeln, Hammams, Festungen, Museen, Minaretten und Basaren. Beginnen Sie mit Taschkent („Steinstadt“), die 2000 Jahre Geschichte hat. Es ist eine moderne Stadt mit Parks, Gärten, Brunnen und Denkmälern, die sich immer wieder ausbreiten und sich von dem sowjetischen architektonischen Still unterscheiden, der  das alte Gesicht der Stadt prägt. <br><br>
Wie andere wichtige Städte des Landes war Taschkent eine Handelskreuzung zwischen Ost und West entlang der Seidenstrasse. Das glänzende Samarkand ist das Kronjuwel des Landes und kann keinesfalls mit einer anderen Stadt verwechselt werden. Wenn Sie in Samarkand sind, verpassen Sie nicht das Mausoleum von Tamerlan, das astronomische Observatorium von Ulugh Beg, Bibi-Chanum-Moschee, Registan (15.-17. Jahrhundert) - eine der schönsten Moscheen der Welt mit ihren mittelalterlichen Universitäten (Medressen), und es gibt noch mehr Orte zu besuchen. Buchara wird Sie mit seiner alten Festung und der Zitadelle von Emir-Ark, ein UNESCO-Weltkulturerbe, überraschen. Schliesslich fahren Sie durch Chiwa - ein Freilichtmuseum. Allein die Innenstadt umfasst 51 Monumentalbauten und nicht weniger als 16 Medressen! <br><br>
Wenn Sie mehr über persische, türkische, arabische, mongolische und russische Kunst wissen möchten, die über Jahrhunderte nicht aufgehört haben zu blühen, ist Usbekistan ideal für jede Art der Reiserouten – Individual- oder Gruppenreisen. Es bleibt nur zu wählen! 
" ,
    "keywords" => "Orient travel, orient, Reise, luxuriös, luxuriöse Reise, luxuriöse Tours, erstklassige Reise,  Hubschrauber-Reise, Hubschrauber-Tours, erstklassiger Zug, Off-road-Tours, luxuriöse Wüstentours, VIP Reiseberatung, Orient Reiseberatung, Orient Reiseführer, personalisierte Reiseplanung, massgeschneiderte Reiseplanung, massgeschneiderte Reise, massgeschneiderte Tour, individuelle Tour, erstklassige Reise nach Usbekistan, hochwertige Dienstleistungen in Usbekistan, luxuriöse Tours in Usbekistan, luxuriöse Hotels in Usbekistan, luxuriöse Reise nach Usbekistan, Reisespezialist für  Usbekistan, VIP Reiseführer in Usbekistan, VIP Reisebegleitung in Usbekistan , erstklassige Reiseberatung für Usbekistan, Tour Spezialist für Usbekistan, live Resieführer in Usbekistan",
    "title" => "Individuelle und Gruppenreisen in Usbekistan | Orient Travel" ,
    "meta_description" => "Wir begleiten Sie bei der Auswahl Ihres Aufenthalts in Kreisläufen in kleinen Gruppen auf den Spuren der antiken Zivilisationen, die das Land geprägt haben. Entdeckungen von Mausoleen, Mederas, Festungen, Minaretten und Moscheen mit blauen Kuppeln. Naturschutzgebiete und riesige Wüste." ,
];


